import {
    faAngleLeft,
    faAngleRight,
    faArrowsAltH,
    faBriefcase,
    faChevronDown,
    faChevronUp,
    faCog,
    faEllipsisV,
    faExclamationCircle,
    faEye,
    faEyeSlash,
    faGamepad,
    faHome,
    faHospitalSymbol,
    faHouseUser,
    faMapMarkerAlt,
    faMoneyBillWave,
    faPhoneAlt,
    faPlusCircle,
    faQuestion,
    faSearch,
    faStethoscope,
    faTachometerAlt,
    faTimes,
    faTrash,
    faUser,
    faUserCircle,
    faStopCircle,
    faRecycle,
    faSyncAlt,
    faPlug,
    faCheckCircle,
} from '@fortawesome/free-solid-svg-icons';

export const GLOBAL_ICONS = {
    angleLeft: faAngleLeft,
    angleRight: faAngleRight,
    mapMarkerAlt: faMapMarkerAlt,
    phoneAlt: faPhoneAlt,
    eye: faEye,
    eyeSlash: faEyeSlash,
    times: faTimes,
    chevronUp: faChevronUp,
    chevronDown: faChevronDown,
    search: faSearch,
    exclamationCircle: faExclamationCircle,
    briefcase: faBriefcase,
    user: faUser,
    cog: faCog,
    plusCircle: faPlusCircle,
    trash: faTrash,
    moneyBillWave: faMoneyBillWave,
    arrowsAltH: faArrowsAltH,
    userCircle: faUserCircle,
    houseUser: faHouseUser,
    home: faHome,
    telemetry: faTachometerAlt,
    gamepad: faGamepad,
    stethoscope: faStethoscope,
    question: faQuestion,
    help: faHospitalSymbol,
    navigate: faEllipsisV,
    stopCircle: faStopCircle,
    recycle: faRecycle,
    syncAlt: faSyncAlt,
    plug: faPlug,
    checkCircle: faCheckCircle,

};
